

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c84cfc2601510aeee9ce93cd1c95ff677ef7e5acb110c337ef48dc5bab9199b2cd6478abea611f008ae25f92fc6b0bb544e74659af4ce3b399dc3e8a9cff1fc3
  stripe_secret_key: <%= ENV["stripe_secret_key"] %>
  stripe_publishable_key: <%= ENV["stripe_publishable_key"] %>
  stripe_endpoint_secret: <%= ENV['endpoint_secret'] %>

test:
  secret_key_base: 9ad3e64ad15bbf92afc847e491b76c8dbea73afb24869d66e0be21f86c91b2e60e6c8023b5d6bb38db60d1e7acb0221a127ceccc51c5f089409e1aaf4c9a3cb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
